{% set name = "facetorch" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd6d1e67036793570c984c390e9623eaae45789ae3eb128c72dc91848d604f08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - codetiming >=1.2.0
    - gdown >=3.11.0
    - googleapis-common-protos >=1.56.3
    - hydra-core >=1.0.0
    - numpy >=1.18.2
    - pip
    - python >=3.8
    - python-json-logger >=2.0.0
    - pytorch >=1.9.0
    - torchvision >=0.10.0

test:
  imports:
    - facetorch
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/tomas-gajarsky/facetorch
  summary: Face analysis PyTorch framework.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  description: |
    A Python library that can detect faces and analyze facial features using neural networks written in PyTorch.
  doc_url: https://tomas-gajarsky.github.io/facetorch/facetorch/index.html
  dev_url: https://github.com/tomas-gajarsky/facetorch

extra:
  recipe-maintainers:
    - tomas-gajarsky
