{% set name = "facetorch" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27f0136a19e454406d9e88d8b5c4b5a7efee8e4957ad655c852bfdbc9fa308c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - huggingface-hub
    - "torch >=1.9,<2.4"
  run:
    - codetiming >=1.2.0
    - gdown >=3.11.0
    - googleapis-common-protos >=1.56.3
    - hydra-core >=1.0.0
    - numpy >=1.18.2
    - pip
    - python >={{ python_min }}
    - python-json-logger >=2.0.0
    - huggingface-hub
    - "torch >=1.9,<2.4"
    - torchvision >=0.10.0

test:
  imports:
    - facetorch
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: https://github.com/tomas-gajarsky/facetorch
  summary: Face analysis PyTorch framework.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  description: |
    A Python library that can detect faces and analyze facial features using neural networks written in PyTorch.
  doc_url: https://tomas-gajarsky.github.io/facetorch/facetorch/index.html
  dev_url: https://github.com/tomas-gajarsky/facetorch

extra:
  recipe-maintainers:
    - tomas-gajarsky
